Services/SupCountUI/SupCountFE.MVC/ViewModels/Group/CreateGroupVM.cs
using System.ComponentModel.DataAnnotations;

namespace SupCountFE.MVC.ViewModels.Group;

public class CreateGroupVM


{
    [Required]
    public string Name { get; set; } = null!;

    [Required]
    public string Description { get; set; } = null!;
}

Services/SupCountUI/SupCountFE.MVC/ViewModels/Group/GroupVM.cs
namespace SupCountFE.MVC.ViewModels.Group
{
    public class GroupVM
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Description { get; set; } = null!;
    }
}

Services/SupCountUI/SupCountFE.MVC/ViewModels/Group/RetournCreatedGroupVM.cs
namespace SupCountFE.MVC.ViewModels.Group;

    public class RetournCreatedGroupVM
    {
        public int Id { get; set; } 
      
    }

Services/SupCountUI/SupCountFE.MVC/ViewModels/Group/UpdateGroupVM.cs
using System.ComponentModel.DataAnnotations;

namespace SupCountFE.MVC.ViewModels.Group
{
    public class UpdateGroupVM
    {
        [Required]
        public int Id { get; set; } 

        [Required(ErrorMessage ="The group Name is required")]
        public string Name { get; set; } = null!;

        [Required]
        public string Description { get; set; } = null!;

    }



}

Services/SupCountUI/SupCountFE.MVC/Controllers/GroupController.cs
using AutoMapper;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.Group;

namespace SupCountFE.MVC.Controllers
{
   
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public GroupController(IGroupService groupService, IMapper mapper, IHttpContextAccessor httpContextAccessor)
        {
            _groupService = groupService;
            _mapper = mapper;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: /Groupe/List
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var groups = await _groupService.GetAllGroupsAsync();
            return View(_mapper.Map<List<GroupVM>>(groups));
        }

        // GET: /Group/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateGroupVM());
        }

        // POST: /Group/Create
        [HttpPost]
        public async Task<IActionResult> Create(CreateGroupVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var result = await _groupService.CreateGroupAsync(model);
            if (result != null)
            {
                TempData["Success"] = "Group created successfully!";
                return RedirectToAction(nameof(List));
            }

            ModelState.AddModelError("", "Failed to create group.");
            return View(model);
        }

        // GET: /Group/Edit/{id}
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var groupeDto = await _groupService.GetGroupByIdAsync(id);
            if (groupeDto == null)
                return NotFound();

            var model = _mapper.Map<UpdateGroupVM>(groupeDto);
            return View(model);
        }

        // POST: /Group/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(UpdateGroupVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            await _groupService.UpdateGroupAsync(model);
            TempData["Success"] = "Group updated successfully!";
            return RedirectToAction(nameof(List));
        }

     
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var group = await _groupService.GetGroupByIdAsync(id);
            if (group == null)
                return NotFound();

            return PartialView("_GroupDetailsPartial", group);
        }


    }
}

Services/SupCountUI/SupCountFE.MVC/Controllers/ReimbursementController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using SupCountFE.MVC.Models;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.Reimbursement;

namespace SupCountFE.MVC.Controllers
{
    public class ReimbursementController : Controller
    {
        private readonly IReimbursementService _reimbursementService;
        private readonly IGroupService _groupService;
        private readonly IUserService _userService;
        private readonly Helper _helper;
        private readonly IMapper _mapper;

        public ReimbursementController(IReimbursementService reimbursementService, IMapper mapper,
            IGroupService groupService, IUserService userService, Helper helper)
        {
            _reimbursementService = reimbursementService;
            _mapper = mapper;
            _groupService = groupService;
            _userService = userService;
            _helper = helper;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var reimbursements = await _reimbursementService.GetAllReimbursementsAsync();
            return View(_mapper.Map<List<ReimbursementVM>>(reimbursements));
        }

        // GET: /Reimbursement/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new CreateReimbursementVM();
            model = await FillListe(model);
            return View(model);
        }

        private async Task<CreateReimbursementVM> FillListe(CreateReimbursementVM model)
        {
            var groups = await _groupService.GetAllGroupsAsync();
            var users = await _userService.GetAllUsersAsync();

            model.GroupsItems = new SelectList(groups, "Id", "Name");
            model.BeneficiariesItems = new SelectList(users.Where(o => o.Id != _helper.UserId).ToList(), "Id", "FullName");

            return model;
        }

        // POST: /Reimbursement/Create
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateReimbursementVM model)
        {
            if (!ModelState.IsValid)
            {
                model = await FillListe(model);
                return View(model);
            }

            var result = await _reimbursementService.CreateReimbursementAsync(model);
            if (result)
            {
                TempData["Success"] = "Reimbursement created successfully!";
                return RedirectToAction(nameof(List));
            }

            ModelState.AddModelError("", "Failed to create reimbursement.");
            model = await FillListe(model);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Generate(int groupId)
        {
            try
            {
                var reimbursements = await _reimbursementService.GenerateReimbursementsAsync(groupId);
                ViewBag.GroupId = groupId;
                return View("Generated", reimbursements);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("List", "Group");
            }
        }

    }
}

Services/SupCountUI/SupCountFE.MVC/Controllers/UserController.cs
using AutoMapper;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.User;

namespace SupCountFE.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        private readonly IRoleService _roleService;

        public UserController(IUserService userService, IMapper mapper, IGroupService groupService,
            IRoleService roleService)
        {
            _userService = userService;
            _mapper = mapper;
            _groupService = groupService;
            _roleService = roleService;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var users = await _userService.GetAllUsersAsync();
            return View(_mapper.Map<List<UserVM>>(users));
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            var model = new RegisterUserVM
            {
                Roles = await _roleService.GetRolesAsync(),
                SelectedRoles = new List<string>() 
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Roles = await _roleService.GetRolesAsync(); 
                return View(model);
            }

            try
            {
                model.Roles = model.SelectedRoles; 
                var createdUser = await _userService.CreateUserAsync(model);
                if (createdUser != null)
                {
                    TempData["Success"] = "User created successfully.";
                    return RedirectToAction(nameof(List));
                }

                ModelState.AddModelError("", "User creation failed.");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.Message}");
            }

            model.Roles = await _roleService.GetRolesAsync(); 
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return RedirectToAction(nameof(List));

            var userToUpdate = await _userService.GetUserByIdAsync(id);
            if (userToUpdate is null)
                return RedirectToAction(nameof(List));

            var model = _mapper.Map<UpdateUserVM>(userToUpdate);

        
            var allRoles = await _roleService.GetRolesAsync();

            var userRoles = userToUpdate.Roles ?? new List<string>();

            model.Roles = allRoles;
            model.SelectedRoles = userRoles;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateUserVM model)
        {
            if (!ModelState.IsValid)
            {
              
                model.Roles = await _roleService.GetRolesAsync();
                return View(model);
            }

            try
            {
                model.Roles = model.SelectedRoles;
                await _userService.UpdateUserAsync(model);

                TempData["Success"] = "User updated successfully.";
                return RedirectToAction(nameof(List));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.Message}");
                model.Roles = await _roleService.GetRolesAsync();
                return View(model);
            }
        }


        // GET: /GroupUser solde
        [HttpGet]
        public async Task<IActionResult> GetUserSoldesByGroupId(int groupId)
        {
            var userSoldes = await _userService.GetUserSoldesByGroupIdAsync(groupId);
            var group = await _groupService.GetGroupByIdAsync(groupId);

            ViewBag.GroupName = group?.Name ?? "Group";

            var viewModel = _mapper.Map<List<SoldeUserVM>>(userSoldes);
            return View("Balances", viewModel);
        }


    }

}

Services/SupCountUI/SupCountFE.MVC/Controllers/UserGroupController.cs
using AutoMapper;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.UserGroup;

namespace SupCountFE.MVC.Controllers
{
    public class UserGroupController : Controller
    {
        private readonly IUserGroupService _userGroupService;
        private readonly IMapper _mapper;

        public UserGroupController(IUserGroupService userGroupService, IMapper mapper)
        {
            _userGroupService = userGroupService;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> Join(int groupId)
        {
            try
            {
                await _userGroupService.JoinGroupAsync(groupId, "Member");
                TempData["Success"] = "Vous avez rejoint le groupe avec succès.";
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message; 
            }

            return RedirectToAction("List", "Group");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var members = await _userGroupService.GetAllAsync();
            return View(_mapper.Map<List<UserGroupVM>>(members));
        }

    }
}

Services/SupCountUI/SupCountFE.MVC/Views/Group/Create.cshtml
@model CreateGroupVM


<div class="container mt-5" style="max-width: 600px;">
    <h3 class="mb-4">Create Group</h3>

    <form asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group mt-3">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control" rows="4"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary btn-block mt-4">Submit</button>
        <a asp-action="List" class="btn btn-outline-secondary btn-block mt-2">Cancel</a>
    </form>
</div>
@section GroupCSS {
    <link rel="stylesheet" href="~/css/form-style.css" />
}

Services/SupCountUI/SupCountFE.MVC/Views/Group/Edit.cshtml
@model SupCountFE.MVC.ViewModels.Group.UpdateGroupVM
<link rel="stylesheet" href="~/css/form-style.css" />
@{
    ViewData["Title"] = "Edit Group";
}

<div class="container mt-5" style="max-width: 600px;">
    <h3 class="mb-4">Edit Group</h3>

    <form asp-action="Edit" method="post">
      

        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Name" class="font-weight-bold"></label>
            <input asp-for="Name" class="form-control" placeholder="Enter group name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group mt-3">
            <label asp-for="Description" class="font-weight-bold"></label>
            <textarea asp-for="Description" class="form-control" rows="4" placeholder="Update description"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary btn-block mt-4">Save Changes</button>
        <a asp-action="List" class="btn btn-outline-secondary btn-block mt-2">Cancel</a>
    </form>
</div>

Services/SupCountUI/SupCountFE.MVC/Views/Group/List.cshtml
@model IEnumerable<GroupVM>

@{
    ViewData["Title"] = "List Groups";
}

<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Groups</h2>
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["Success"]
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span>&times;</span></button>
            </div>
        }
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                @TempData["Error"]
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span>&times;</span></button>
            </div>
        }

        <a class="btn btn-outline-primary" asp-action="Create">+ New Group</a>
    </div>

    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th style="width: 300px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="User" asp-action="GetUserSoldesByGroupId" asp-route-groupId="@group.Id" class="text-decoration-none font-weight-bold">
                            @group.Name
                        </a>
                    </td>

                    <td>
                        <a class="btn btn-sm btn-secondary" asp-action="Edit" asp-route-id="@group.Id">Edit</a>

                        <button class="btn btn-sm btn-info text-white"
                                data-toggle="modal"
                                data-target="#detailsModal"
                                data-id="@group.Id"
                                data-name="@group.Name"
                                data-description="@group.Description">
                            Details
                        </button>

                        <form asp-action="Join" asp-controller="UserGroup" method="post" style="display:inline;">
                            <input type="hidden" name="groupId" value="@group.Id" />
                            <button type="submit" class="btn btn-sm btn-success">Join</button>
                        </form>

                        <form asp-action="Generate" asp-controller="Reimbursement" method="get" style="display:inline;">
                            <input type="hidden" name="groupId" value="@group.Id" />
                            <button type="submit" class="btn btn-sm btn-warning">Balance</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Details Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="detailsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content shadow-lg border-0 rounded">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="detailsModalLabel">
                    <i class="fas fa-users mr-2"></i> Group Details
                </h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </button>
            </div>

            <div class="modal-body px-4 py-3">
                <div class="mb-3">
                    <label class="font-weight-bold text-secondary mb-0">Name:</label>
                    <div class="text-dark" id="modalGroupName">Loading...</div>
                </div>
                <div>
                    <label class="font-weight-bold text-secondary mb-0">Description:</label>
                    <div class="text-dark" id="modalGroupDescription" style="white-space: pre-wrap;">Loading...</div>
                </div>
            </div>

            <div class="modal-footer justify-content-end">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section GroupJS {
    <script>
        $('#detailsModal').on('show.bs.modal', function (event) {
            const button = $(event.relatedTarget);
            $('#modalGroupName').text(button.data('name') || 'N/A');
            $('#modalGroupDescription').text(button.data('description') || 'No description provided.');
        });
    </script>
}

Services/SupCountUI/SupCountFE.MVC/Views/Group/_GroupDetailsPartial.cshtml
@model SupCountBE.Application.Responses.Group.GroupResponse

<div>
    <p><strong>Description:</strong></p>
    <p style="white-space: pre-wrap;">@Model.Description</p>
</div>