Services/SupCountUI/SupCountFE.MVC/Controllers/CategoryController.cs
using AutoMapper;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.Category;

namespace SupCountFE.MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public CategoryController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var categories = await _categoryService.GetAllAsync();
            return View (_mapper.Map<List<CategoryVM>>(categories));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateCategoryVM());
        }

        [HttpPost]
     
        public async Task<IActionResult> Create(CreateCategoryVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var result = await _categoryService.CreateAsync(model);
            if (result != null)
            {
                TempData["Success"] = "Category created successfully!";
                return RedirectToAction("List");
            }

            ModelState.AddModelError("", "Failed to create category.");
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var category = await _categoryService.GetByIdAsync(id);
            if (category == null)
                return NotFound();

            var model = new UpdateCategoryVM
            {
                Id = category.Id,
                Name = category.Name
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UpdateCategoryVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            await _categoryService.UpdateAsync(model);
            TempData["Success"] = "Category updated successfully!";
            return RedirectToAction("List");
        }

    }
}

Services/SupCountUI/SupCountFE.MVC/Controllers/ExpenseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using SupCountFE.MVC.Models;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.Expense;
using SupCountFE.MVC.ViewModels.Participation;

namespace SupCountFE.MVC.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        private readonly ICategoryService _categoryService;
        private readonly IParticipationService _participationService;
        private readonly IJustificationService justificationService;
        private readonly Helper _helper;
        public ExpenseController(IExpenseService expenseService, IMapper mapper, IGroupService groupService,
          ICategoryService categoryService, IJustificationService justificationService, Helper helper, IParticipationService participationService)
        {
            _expenseService = expenseService;
            _mapper = mapper;
            _groupService = groupService;
            _categoryService = categoryService;
            this.justificationService = justificationService;
            _participationService = participationService;
            _helper = helper;
        }

        // action Participate
        [HttpGet]
        public async Task<IActionResult> Participate(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var expense = await _expenseService.GetExpenseByIdAsync(id.Value);
            if (expense == null)
            {
                return NotFound();
            }
            var model = new ParticipateExpenseVM { ExpenseId = id.Value, ExpenseTitle = expense.Title, Weight = 100 };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Participate(ParticipateExpenseVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _participationService.CreateParticipationAsync(model.ExpenseId!.Value, model.Weight);
                return RedirectToAction("List","Participation");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }


        [HttpGet]
        public IActionResult Dwonload(string Base64String)
        {

            try
            {
                var fileBytes = Convert.FromBase64String(Base64String);

                return File(fileBytes, "application/octet-stream", "Justification");
            }
            catch (FormatException)
            {
                return BadRequest("Invalid base64 string format.");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Justifications(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var justifications = await justificationService.GetListAsync(id.Value);
            return View(_mapper.Map<IList<JustificationExepnseVM>>(justifications));
        }
      

        // GET: /Expense/List
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var expenses = await _expenseService.GetAllExpensesAsync();
            return View(_mapper.Map<List<ExpenseVM>>(expenses));
        }

        // GET: /Expense/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new CreateExpenseVM();
            model = await FillListe(model);

            return View(model);
        }

        private async Task<CreateExpenseVM> FillListe(CreateExpenseVM model)
        {
            var groups = await _groupService.GetAllGroupsAsync();
            var categories = await _categoryService.GetAllAsync();

            model.GroupsItems = new SelectList(groups, "Id", "Name");
            model.CategoriesItems = new SelectList(categories, "Id", "Name");

            return model;
        }


        // POST: /Expense/Create
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateExpenseVM model)
        {
            if (!ModelState.IsValid)
            {
                model = await FillListe(model);
                return View(model);
            }

            var result = await _expenseService.CreateExpenseAsync(model);
            if (result != null)
            {
                TempData["Success"] = "Expense created successfully!";
                return RedirectToAction(nameof(List));
            }

            ModelState.AddModelError("", "Failed to create expense.");

            var g = await _groupService.GetAllGroupsAsync();
            var c = await _categoryService.GetAllAsync();
            ViewBag.Groups = new SelectList(g, "Id", "Name");
            ViewBag.Categories = new SelectList(c, "Id", "Name");
            return View(model);
        }


        // GET: /Expense/Edit/{id}
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var expense = await _expenseService.GetExpenseByIdAsync(id);
            if (expense == null)
                return NotFound();

            var model = _mapper.Map<UpdateExpenseVM>(expense);
            return View(model);
        }

        // POST: /Expense/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(UpdateExpenseVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            await _expenseService.UpdateExpenseAsync(model);
            TempData["Success"] = "Expense updated successfully!";
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public async Task<IActionResult> Statistics()
        {
            var userId = _helper.UserId;
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToAction("Login", "Account");
            }

            var stats = await _expenseService.GetUserExpenseStatisticsAsync(userId);
            return View(stats);
        }
        [HttpGet]
        public async Task<IActionResult> ExportCsv(int groupId)
        {
            var stream = await _expenseService.ExportExpensesCsvAsync(groupId);
            if (stream == null)
                return BadRequest("Erreur lors de l'export CSV.");

            return File(stream, "text/csv", $"Expenses_Group_{groupId}.csv");
        }

        [HttpGet]
        public async Task<IActionResult> ExportPdf(int groupId)
        {
            var stream = await _expenseService.ExportExpensesPdfAsync(groupId);
            if (stream == null)
                return BadRequest("Erreur lors de l'export PDF.");

            return File(stream, "application/pdf", $"Expenses_Group_{groupId}.pdf");
        }




    }
}

Services/SupCountUI/SupCountFE.MVC/Controllers/GroupController.cs
using AutoMapper;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.Group;

namespace SupCountFE.MVC.Controllers
{
   
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public GroupController(IGroupService groupService, IMapper mapper, IHttpContextAccessor httpContextAccessor)
        {
            _groupService = groupService;
            _mapper = mapper;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: /Groupe/List
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var groups = await _groupService.GetAllGroupsAsync();
            return View(_mapper.Map<List<GroupVM>>(groups));
        }

        // GET: /Group/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateGroupVM());
        }

        // POST: /Group/Create
        [HttpPost]
        public async Task<IActionResult> Create(CreateGroupVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var result = await _groupService.CreateGroupAsync(model);
            if (result != null)
            {
                TempData["Success"] = "Group created successfully!";
                return RedirectToAction(nameof(List));
            }

            ModelState.AddModelError("", "Failed to create group.");
            return View(model);
        }

        // GET: /Group/Edit/{id}
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var groupeDto = await _groupService.GetGroupByIdAsync(id);
            if (groupeDto == null)
                return NotFound();

            var model = _mapper.Map<UpdateGroupVM>(groupeDto);
            return View(model);
        }

        // POST: /Group/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(UpdateGroupVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            await _groupService.UpdateGroupAsync(model);
            TempData["Success"] = "Group updated successfully!";
            return RedirectToAction(nameof(List));
        }

     
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var group = await _groupService.GetGroupByIdAsync(id);
            if (group == null)
                return NotFound();

            return PartialView("_GroupDetailsPartial", group);
        }


    }
}

Services/SupCountUI/SupCountFE.MVC/Controllers/MessageController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using SupCountBE.Application.Commands.Message;
using SupCountFE.MVC.Models;
using SupCountFE.MVC.Services.Contracts;
using SupCountFE.MVC.ViewModels.Message;

namespace SupCountFE.MVC.Controllers;

public class MessageController : Controller
{
    #region Fileds & ctor
    private readonly IMessageService _messageService;
    private readonly IGroupService _groupService;
    private readonly IUserService _userService;
    private readonly Helper _helper;
    private readonly IMapper _mapper;

    public MessageController(
        IMessageService messageService,
        Helper helper,
        IGroupService groupService,
        IUserService userService,
        IMapper mapper)
    {
        _messageService = messageService;
        _helper = helper;
        _groupService = groupService;
        _userService = userService;
        _mapper = mapper;
    }

    #endregion

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var messages = await _messageService.GetAllMessagesAsync();
        return View(messages);
    }
    [HttpGet]
    public async Task<IActionResult> Private()
    {
        var userId = _helper.UserId!;
        var messages = await _messageService.GetPrivateMessagesAsync();
        var users = await _userService.GetAllUsersAsync();
        ViewBag.Users = users
            .Where(u => u.Id != userId)
            .Select(u => new SelectListItem
            {
                Value = u.Id,
                Text = u.FullName
            }).ToList();
        ViewBag.SenderId = userId;

        return View(messages);
    }


    [HttpPost]
    public async Task<IActionResult> SendPrivate(CreatePrivateMessageCommand model)
    {

        if (string.IsNullOrWhiteSpace(model.Content) || string.IsNullOrEmpty(model.RecipientId))
        {
            ModelState.AddModelError("", "Message or recipient missing.");
            return RedirectToAction("Private", new { recipientId = model.RecipientId });
        }

        await _messageService.SendMessageAsync(model);

        return RedirectToAction(nameof(Private));
    }


    [HttpGet]
    public async Task<IActionResult> Create(int? groupId)
    {
        var userId = _helper.UserId!;
        if (groupId == null)
        {
            ModelState.AddModelError("", "Group ID is required.");
            return View(new CreateMessageVM { GroupsItems = new SelectList(await _groupService.GetAllGroupsAsync(), "Id", "Name") });
        }

        var model = new CreateMessageVM
        {
            SenderId = userId,
            GroupId = groupId,
            GroupsItems = new SelectList(await _groupService.GetAllGroupsAsync(), "Id", "Name"),
            Messages = await _messageService.GetMessagesAsync(userId, groupId.Value)
        };

        return View(model);
    }


    [HttpPost]
    public async Task<IActionResult> Create(CreateMessageVM model)
    {

        if (model.GroupId == null)
        {
            ModelState.AddModelError("", "Group ID is required.");
            model.GroupsItems = new SelectList(await _groupService.GetAllGroupsAsync(), "Id", "Name");
            return View(model);
        }
        model.SenderId = _helper.UserId!;



        if (!ModelState.IsValid)
        {
            model.GroupsItems = new SelectList(await _groupService.GetAllGroupsAsync(), "Id", "Name");
            model.Messages = await _messageService.GetMessagesAsync(model.SenderId, model.GroupId.Value);
            return View(model);
        }

        var command = _mapper.Map<CreateMessageCommand>(model);
        var result = await _messageService.SendMessageAsync(command);

        if (result != null)
        {
            TempData["Success"] = "Message sent successfully!";
            return RedirectToAction(nameof(Create), new { groupId = model.GroupId });
        }

        ModelState.AddModelError("", "Failed to send the message.");
        model.GroupsItems = new SelectList(await _groupService.GetAllGroupsAsync(), "Id", "Name");
        model.Messages = await _messageService.GetMessagesAsync(model.SenderId, model.GroupId.Value);
        return View(model);
    }

}

Services/SupCountUI/SupCountFE.MVC/Views/Shared/_Layout.cshtml
@inject Helper _helper
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>SupCount - @ViewData["title"]</title>

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,600,700,800,900" rel="stylesheet" />
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" asp-append-version="true" />

    @RenderSection("ExpenseCSS", false)
	@RenderSection("GroupCSS", false)
    @RenderSection("CategoryCSS", false)
    @RenderSection("UserCSS", false)
	@RenderSection("UserGroupCSS", false)
    @RenderSection("ReimbursementCSS", false)
    @RenderSection("ParticipationCSS", false)

 

</head>
<body id="page-top">

    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Dashboard" asp-action="Index">
                <div class="sidebar-brand-text mx-3">SUPCOUNT</div>
            </a>
               @if (_helper.UserRoles.Contains("User"))
            {
                  <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
                 <div class="sidebar-heading">Interface</div>

            <!-- Expenses -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseExpenses">
                    <i class="fas fa-money-bill-wave"></i>
                    <span>Expenses</span>
                </a>
               <div id="collapseExpenses" class="collapse" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" asp-controller="Expense" asp-action="List">All Expenses</a>
                     <a class="collapse-item" asp-controller="Participation" asp-action="List">All Participations</a>
                </div>
            </div>

            </li>

            <!-- Reimbursements -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReimbursements">
                    <i class="fas fa-receipt"></i>
                    <span>Reimbursements</span>
                </a>
                <div id="collapseReimbursements" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Reimbursement" asp-action="List">My Reimbursements</a>
                    </div>
                </div>
            </li>
            <!-- Groups -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseGroups">
                    <i class="fas fa-users"></i>
                    <span>Groups</span>
                </a>
                <div id="collapseGroups" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Group" asp-action="List">All Groups</a>
                        <a class="collapse-item" asp-controller="UserGroup" asp-action="List">Group Members</a>
                      

                    </div>
                </div>
            </li>
            <!-- Categories -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCategories" aria-expanded="false" aria-controls="collapseCategories">
                    <i class="fas fa-tags"></i>
                    <span>Categories</span>
                </a>
                <div id="collapseCategories" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Category" asp-action="List">All Categories</a>                
                    </div>
                </div>
            </li>
            <!-- Statistics -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseStatistics" aria-expanded="false" aria-controls="collapseStatistics">
                    <i class="fas fa-chart-bar"></i>
                    <span>Statistics</span>
                </a>
                <div id="collapseStatistics" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Expense" asp-action="Statistics">Overview</a>
                     
                    </div>
                </div>
            </li>
          
          <!-- Messages -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMessages"
                   aria-expanded="true" aria-controls="collapseMessages">
                    <i class="fas fa-envelope"></i>
                    <span>Messages</span>
                </a>
                <div id="collapseMessages" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Messaging</h6>
                     
                        <a class="collapse-item" asp-controller="Message" asp-action="Create">Group Messages</a>
                         <a class="collapse-item" asp-controller="Message" asp-action="Private">Private Messages</a>
                    </div>
                </div>
            </li>

                
            }

           
            @if (_helper.UserRoles.Contains("Admin"))
            {
                <!-- Admin Panel -->
                <div class="sidebar-heading">Admin</div>
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages">
                        <i class="fas fa-fw fa-folder"></i>
                        <span>Admin Panel</span>
                    </a>
                    <div id="collapsePages" class="collapse" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Login Screens:</h6>
                            <a class="collapse-item" asp-controller="User" asp-action="Register">Register</a>
                            <a class="collapse-item" asp-controller="User" asp-action="List">All Users</a>
                        </div>
                    </div>
                </li>
}

        </ul>

        <!-- Sidebar Toggler -->
        <hr class="sidebar-divider d-none d-md-block" />
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 shadow">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" data-toggle="dropdown">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@_helper.UserName</span>
                                <img class="img-profile rounded-circle" src="~/img/undraw_profile.svg" />
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                              
                                <div class="dropdown-divider"></div>
                                <form asp-controller="Auth" asp-action="Logout" method="post" class="d-inline">
                                    <button type="submit" class="dropdown-item bg-transparent border-0">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Logout
                                    </button>
                                </form>

                            </div>
                        </li>
                    </ul>
                </nav>

                <!-- Main Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="text-center my-auto">
                        <span>Copyright &copy; SupCount @DateTime.UtcNow.Year</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

   

    <script src="~/vendor/jquery/jquery.min.js" asp-append-version="true"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/vendor/jquery-easing/jquery.easing.min.js" asp-append-version="true"></script>
    <script src="~/js/sb-admin-2.min.js" asp-append-version="true"></script>
    <script src="~/vendor/chart.js/Chart.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("ExpenseJS", false)
    @RenderSection("GroupJS", false)
	@RenderSection("UserJS", false)
	@RenderSection("UserGroupJS", false)"
    @RenderSection("ReimbursementJS", false)
    @RenderSection("StatisticsJS", false)
    @RenderSection("MessageJS", false)
    @RenderSection("PrivateMessageJS", false)


</body>
</html>